[build-system]
requires = [
    "cmake>=3.18",
    "setuptools>=42",
    "wheel",
    "shiboken6",
]

build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
before-all = "cibuildwheel/before_all.sh"
build-verbosity = 1