name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.15.0
        env:
          CIBW_BUILD: "cp39-manylinux_2_28"
          CIBW_ENVIRONMENT_ALL: "QT_VERSION=6.4.2 AQTINSTALL_VERSION=3.1.6"
          CIBW_BEFORE_ALL_LINUX: >
            pipx install aqtinstall==$AQTINSTALL_VERSION

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
