name: Build

on: [push, pull_request]

env:
  AQTINSTALL_VERSION: "3.1.6"
  QT_VERSION: "6.4.2"

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.15.0
        env:
          CIBW_BUILD: "cp39-manylinux*"
          CIBW_ARCHS_LINUX: "x86_64"
          CIBW_MANYLINUX_X86_64_IMAGE: ghcr.io/python-limereport/manylinux_2_28_x86_64:qt-6.4.2
          # CIBW_ENVIRONMENT_ALL: "QT_VERSION=6.4.2 AQTINSTALL_VERSION=3.1.6"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
